env:
  rom: "Pokemon Blue.gb"
  window: "SDL2"
  speed: 1.0
  ring_slots: 8
perception:
  z_dim: 256
  smooth_tau: 0.9
  rnd_dim: 128
  use_ram: true
tile_descriptor:
  tile_size: 8
  embedding_dim: 64
  codebook_size: 64
training:
  algo: "ppo"
  num_actors: 1
  steps_per_actor: 8
  total_updates: 1
  lr: 3e-4
  gamma: 0.997
  lam: 0.95
  clip: 0.1
  c1: 0.5
  c2: 0.01
  entropy_coef: 0.01
  warmup_steps: 8
policy:
  hidden_dim: 256
  num_skills: 4
  skill_vocab: ["NAVIGATE","INTERACT","MENU_SEQUENCE","WAIT"]
  gate_temp_start: 1.0
  gate_temp_end: 0.1
  gate_reg: 0.001
nav_planner:
  thompson_retries: 8
  epsilon: 1e-2
executor:
  watchdog_steps: 90
brain:
  attach_screenshot: true
  enabled: true
  model: "gpt-5-mini"
  max_output_tokens: 100000
  candidate_preview: 8
  enable_web_search: false
  use_for_rollouts: false
  max_directive_age_steps: 1200
  min_candidate_overlap: 2
  halt_cooldown_steps: 180
  naming_cooldown_steps: 600
  naming_retry_guard_steps: 240
  naming_fallback_limit: 6
  novelty_halt_cooldown_steps: 600
